name: Documentation

on: push

jobs:
  documentation:
    name: Documentation

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Push documentation to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: 'doc'
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
