name: PHP

on:
  push:
    branches:
      - master

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  php:
    name: Test PHP ${{ matrix.php-versions }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.4' ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install the dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: composer run-script test

      - name: Analyse with PHPStan
        run: composer run-script phpstan
