name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta-[0-9]+'

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Prepare environment variables
        run: |
          echo "SERVER_URL=$GITHUB_SERVER_URL" >> $GITHUB_ENV
          echo "REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          echo "VERSION=$(echo "$GITHUB_REF" | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --no-progress

      - name: Create application
        id: create_application
        run: |
          tar czf application config res src vendor cli.php composer.json composer.lock LICENSE README.md

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body: |
            See [changelog](${{ env.SERVER_URL }}/${{ env.REPOSITORY }}/blob/master/CHANGELOG.md#${{ env.VERSION }}).
          draft: false
          prerelease: ${{ contains(env.VERSION, '-beta') || contains(env.VERSION, '-dev') }}

      - name: Add application
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: application
          asset_name: Backup.tar.gz
          asset_content_type: application/gzip
